<a href="https://colab.research.google.com/github/Teriekarie/DSCI_SGA/blob/main/Movies_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [106]:
# from google.colab import drive
# drive.mount('/content/drive')

In [107]:
%cd /content/drive/MyDrive/STUTERN 1.3 ASSIGNMENT/module8

/content/drive/MyDrive/STUTERN 1.3 ASSIGNMENT/module8

In [108]:
#Import Dependencies
import numpy as np 
import pandas as pd

In [185]:
#Load csv File
movies= pd.read_csv('/content/drive/MyDrive/STUTERN 1.3 ASSIGNMENT/module8/movies.csv')
movies

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
9994,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n \n Stars:\nMorgan Taylor Camp...,NaN,NaN,NaN
9995,Arcane,(2021– ),"\nAnimation, Action, Adventure",NaN,\nAdd a Plot\n,\n,NaN,NaN,NaN
9996,Heart of Invictus,(2022– ),"\nDocumentary, Sport",NaN,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN
9997,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN
9998,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN

Formating the column names

In [186]:
movies.columns = movies.columns.str.upper()
movies.columns

Index(['MOVIES', 'YEAR', 'GENRE', 'RATING', 'ONE-LINE', 'STARS', 'VOTES',
       'RUNTIME', 'GROSS'],
      dtype='object')

Changing the ONE-LINE colunmn name to SYNOPSIS

In [187]:
movies.rename= movies.rename(columns = {'ONE-LINE':'SYNOPSIS'}, inplace=True)
movies.rename

In [188]:
#Check for Missing Values in the dataframe
movies.isnull().any().any()

True

In [189]:
#Check for Missing Values in each column of the Dataset
movies.isnull().any()

MOVIES      False
YEAR         True
GENRE        True
RATING       True
SYNOPSIS    False
STARS       False
VOTES        True
RUNTIME      True
GROSS        True
dtype: bool

This shows the column with the empty cells

In [190]:
#Check for the total missing values in each column
movies.isnull().sum()

MOVIES         0
YEAR         644
GENRE         80
RATING      1820
SYNOPSIS       0
STARS          0
VOTES       1820
RUNTIME     2958
GROSS       9539
dtype: int64

Cleaning the empty columns.
Lets replace the rating, votes and runtime with the average of each column and drop the year and genre as such column can not be assumed.

In [191]:
#converting the datatype of votes to be able to get the mean
#Removing Comma from 'VOTES' column
movies['VOTES'] = movies['VOTES'].astype(str)
movies['VOTES'] = [x.replace(',','') for x in movies["VOTES"]]
# convert "VOTES" from string to float
movies['VOTES'] = movies['VOTES'].astype(float)
#correct data types of columns
movies.dtypes

MOVIES       object
YEAR         object
GENRE        object
RATING      float64
SYNOPSIS     object
STARS        object
VOTES       float64
RUNTIME     float64
GROSS        object
dtype: object

In [192]:
# replacing the column
movies_runtime= movies['RUNTIME'].fillna(movies['RUNTIME'].mean(), inplace=True)

#fill the rating columns
movies_rating= movies['RATING'].fillna(movies['RATING'].mean(), inplace=True)

#fill the votes column
movies_votes = movies['VOTES'].fillna(movies['VOTES'].mean(), inplace=True)

# Fill up empty spaces  for 'Gross' column with 0
movies['GROSS'].fillna(0, inplace=True)

# Dropping rows with missing values in Year and Genre
movies.dropna(axis='index', how='any', subset=['YEAR', 'GENRE'], inplace=True)

movies

,MOVIES,YEAR,GENRE,RATING,SYNOPSIS,STARS,VOTES,RUNTIME,GROSS
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.100000,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,21062.000000,121.000000,0
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.000000,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...",17870.000000,25.000000,0
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.200000,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...",885805.000000,44.000000,0
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.200000,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...",414849.000000,23.000000,0
4,Army of Thieves,(2021),"\nAction, Crime, Horror",6.921176,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,15124.062722,68.688539,0
...,...,...,...,...,...,...,...,...,...
9994,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",6.921176,\nAdd a Plot\n,\n \n Stars:\nMorgan Taylor Camp...,15124.062722,68.688539,0
9995,Arcane,(2021– ),"\nAnimation, Action, Adventure",6.921176,\nAdd a Plot\n,\n,15124.062722,68.688539,0
9996,Heart of Invictus,(2022– ),"\nDocumentary, Sport",6.921176,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,15124.062722,68.688539,0
9997,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",6.921176,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,15124.062722,68.688539,0
9998,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",6.921176,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,15124.062722,68.688539,0

In [193]:
movies.isnull().sum()

MOVIES      0
YEAR        0
GENRE       0
RATING      0
SYNOPSIS    0
STARS       0
VOTES       0
RUNTIME     0
GROSS       0
dtype: int64

Now we have all the rows in the dataframe filled up

In [194]:
#Checking for duplicates
movies.duplicated().any()

True

In [195]:
# removing the duplicates
movies.drop_duplicates(inplace= True)
movies.duplicated().sum()

0

Final touch to ensure the dataframe is clean and ready for use

In [196]:
#More Data cleaning to make the dataset neat
#Removing the next line(\n) value from the columns
movies["GENRE"] = movies["GENRE"].astype(str)
movies["GENRE"] = [x.replace('\n','') for x in movies["GENRE"]]


movies["SYNOPSIS"] = movies["SYNOPSIS"].astype(str)
movies["SYNOPSIS"] = [x.replace('\n','') for x in movies["SYNOPSIS"]]

movies["STARS"] = movies["STARS"].astype(str)
movies["STARS"] = [x.replace('\n','') for x in movies["STARS"]]

movies

,MOVIES,YEAR,GENRE,RATING,SYNOPSIS,STARS,VOTES,RUNTIME,GROSS
0,Blood Red Sky,(2021),"Action, Horror, Thriller",6.100000,A woman with a mysterious illness is forced in...,Director:Peter Thorwarth| Stars:Peri B...,21062.000000,121.000000,0
1,Masters of the Universe: Revelation,(2021– ),"Animation, Action, Adventure",5.000000,The war for Eternia begins again in what may b...,"Stars:Chris Wood, Sarah Michel...",17870.000000,25.000000,0
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",8.200000,Sheriff Deputy Rick Grimes wakes up from a com...,"Stars:Andrew Lincoln, Norman R...",885805.000000,44.000000,0
3,Rick and Morty,(2013– ),"Animation, Adventure, Comedy",9.200000,An animated series that follows the exploits o...,"Stars:Justin Roiland, Chris Pa...",414849.000000,23.000000,0
4,Army of Thieves,(2021),"Action, Crime, Horror",6.921176,"A prequel, set before the events of Army of th...",Director:Matthias Schweighöfer| Stars:...,15124.062722,68.688539,0
...,...,...,...,...,...,...,...,...,...
9993,Totenfrau,(2022– ),"Drama, Thriller",6.921176,Add a Plot,Director:Nicolai Rohde| Stars:Felix Kl...,15124.062722,68.688539,0
9995,Arcane,(2021– ),"Animation, Action, Adventure",6.921176,Add a Plot,,15124.062722,68.688539,0
9996,Heart of Invictus,(2022– ),"Documentary, Sport",6.921176,Add a Plot,Director:Orlando von Einsiedel| Star:P...,15124.062722,68.688539,0
9997,The Imperfects,(2021– ),"Adventure, Drama, Fantasy",6.921176,Add a Plot,Director:Jovanka Vuckovic| Stars:Morga...,15124.062722,68.688539,0
9998,The Imperfects,(2021– ),"Adventure, Drama, Fantasy",6.921176,Add a Plot,Director:Jovanka Vuckovic| Stars:Morga...,15124.062722,68.688539,0